// axios actions
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";

//local transaction actions
export const FILTER_TRANSACTIONS = "FILTER_TRANSACTIONS";

// auth actions
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// frontend error actions
// oppertion error
export const EMPTY_TEXT_ERROR = "EMPTY_TEXT_ERROR";
// auth error
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
// backend error
export const GET_TRANSACTIONS_ERROR = "GET_TRANSACTIONS_ERROR";
export const ADD_TRANSACTION_ERROR = "ADD_TRANSACTION_ERROR";
export const DELETE_TRANSACTION_ERROR = "DELETE_TRANSACTION_ERROR";
export const UPDATE_TRANSACTION_ERROR = "ADD_TRANSACTION_ERROR";
