# Generated by Django 3.2.9 on 2021-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_transaction_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='onwer',
            new_name='owner',
        ),
    ]
