# Generated by Django 3.2.9 on 2021-12-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_transaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='text',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
