# Generated by Django 3.2.9 on 2021-12-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20211217_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
